<?php
define("js_undefined_str", "__undefined__");
define("js_typeof_str", "__typeof__");
define("js_void_str", "__void__");
define("js_null_str", "__null__");
define("js_false_str", "__false__");
define("js_true_str", "__true__");
define("js_throw_str", "__throw__");
define("js_in_str", "__in__");
define("js_instanceof_str", "__instanceof__");
/*
 * op
 * val
 * name
 * image
 * len
 * use
 * def
 * format
 */
$opcodes = [
    ["JSOP_NOP", 0, "nop", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_UNDEFINED", 1, js_undefined_str, "", 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_GETRVAL", 2, "getrval", NULL, 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_ENTERWITH", 3, "enterwith", NULL, 5, 1, 0, ["JOF_SCOPE"]],
    ["JSOP_LEAVEWITH", 4, "leavewith", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_RETURN", 5, "return", NULL, 1, 1, 0, ["JOF_BYTE"]],
    ["JSOP_GOTO", 6, "goto", NULL, 5, 0, 0, ["JOF_JUMP"]],
    ["JSOP_IFEQ", 7, "ifeq", NULL, 5, 1, 0, ["JOF_JUMP", "JOF_DETECTING"]],
    ["JSOP_IFNE", 8, "ifne", NULL, 5, 1, 0, ["JOF_JUMP"]],
    ["JSOP_ARGUMENTS", 9, "arguments", NULL, 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_SWAP", 10, "swap", NULL, 1, 2, 2, ["JOF_BYTE"]],
    ["JSOP_POPN", 11, "popn", NULL, 3, -1, 0, ["JOF_UINT16"]],
    ["JSOP_DUP", 12, "dup", NULL, 1, 1, 2, ["JOF_BYTE"]],
    ["JSOP_DUP2", 13, "dup2", NULL, 1, 2, 4, ["JOF_BYTE"]],
    ["JSOP_CHECKISOBJ", 14, "checkisobj", NULL, 2, 1, 1, ["JOF_UINT8"]],
    ["JSOP_BITOR", 15, "bitor", "|", 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
    ["JSOP_BITXOR", 16, "bitxor", "^", 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
    ["JSOP_BITAND", 17, "bitand", "&", 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
    ["JSOP_EQ", 18, "eq", "==", 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH", "JOF_DETECTING"]],
    ["JSOP_NE", 19, "ne", "!=", 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH", "JOF_DETECTING"]],
    ["JSOP_LT", 20, "lt", "<", 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
    ["JSOP_LE", 21, "le", "<=", 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
    ["JSOP_GT", 22, "gt", ">", 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
    ["JSOP_GE", 23, "ge", ">=", 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
    ["JSOP_LSH", 24, "lsh", "<<", 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
    ["JSOP_RSH", 25, "rsh", ">>", 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
    ["JSOP_URSH", 26, "ursh", ">>>", 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
    ["JSOP_ADD", 27, "add", "+", 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
    ["JSOP_SUB", 28, "sub", "-", 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
    ["JSOP_MUL", 29, "mul", "*", 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
    ["JSOP_DIV", 30, "div", "/", 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
    ["JSOP_MOD", 31, "mod", "%", 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
    ["JSOP_NOT", 32, "not", "!", 1, 1, 1, ["JOF_BYTE", "JOF_ARITH", "JOF_DETECTING"]],
    ["JSOP_BITNOT", 33, "bitnot", "~", 1, 1, 1, ["JOF_BYTE", "JOF_ARITH"]],
    ["JSOP_NEG", 34, "neg", "- ", 1, 1, 1, ["JOF_BYTE", "JOF_ARITH"]],
    ["JSOP_POS", 35, "pos", "+ ", 1, 1, 1, ["JOF_BYTE", "JOF_ARITH"]],
    ["JSOP_DELNAME", 36, "delname", NULL, 5, 0, 1, ["JOF_ATOM", "JOF_NAME", "JOF_CHECKSLOPPY"]],
    ["JSOP_DELPROP", 37, "delprop", NULL, 5, 1, 1, ["JOF_ATOM", "JOF_PROP", "JOF_CHECKSLOPPY"]],
    ["JSOP_DELELEM", 38, "delelem", NULL, 1, 2, 1, ["JOF_BYTE", "JOF_ELEM", "JOF_CHECKSLOPPY"]],
    ["JSOP_TYPEOF", 39, js_typeof_str, NULL, 1, 1, 1, ["JOF_BYTE", "JOF_DETECTING"]],
    ["JSOP_VOID", 40, js_void_str, NULL, 1, 1, 1, ["JOF_BYTE"]],
    ["JSOP_SPREADCALL", 41, "spreadcall", NULL, 1, 3, 1, ["JOF_BYTE", "JOF_INVOKE", "JOF_TYPESET"]],
    ["JSOP_SPREADNEW", 42, "spreadnew", NULL, 1, 4, 1, ["JOF_BYTE", "JOF_INVOKE", "JOF_TYPESET"]],
    ["JSOP_SPREADEVAL", 43, "spreadeval", NULL, 1, 3, 1, ["JOF_BYTE", "JOF_INVOKE", "JOF_TYPESET", "JOF_CHECKSLOPPY"]],
    ["JSOP_DUPAT", 44, "dupat", NULL, 4, 0, 1, ["JOF_UINT24"]],
    ["JSOP_SYMBOL", 45, "symbol", NULL, 2, 0, 1, ["JOF_UINT8"]],
    ["JSOP_STRICTDELPROP", 46, "strict-delprop", NULL, 5, 1, 1, ["JOF_ATOM", "JOF_PROP", "JOF_CHECKSTRICT"]],
    ["JSOP_STRICTDELELEM", 47, "strict-delelem", NULL, 1, 2, 1, ["JOF_BYTE", "JOF_ELEM", "JOF_CHECKSTRICT"]],
    ["JSOP_STRICTSETPROP", 48, "strict-setprop", NULL, 5, 2, 1, ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSTRICT"]],
    ["JSOP_STRICTSETNAME", 49, "strict-setname", NULL, 5, 2, 1, ["JOF_ATOM", "JOF_NAME", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSTRICT"]],
    ["JSOP_STRICTSPREADEVAL", 50, "strict-spreadeval", NULL, 1, 3, 1, ["JOF_BYTE", "JOF_INVOKE", "JOF_TYPESET", "JOF_CHECKSTRICT"]],
    ["JSOP_CLASSHERITAGE", 51, "classheritage", NULL, 1, 1, 2, ["JOF_BYTE"]],
    ["JSOP_FUNWITHPROTO", 52, "funwithproto", NULL, 5, 1, 1, ["JOF_OBJECT"]],
    ["JSOP_GETPROP", 53, "getprop", NULL, 5, 1, 1, ["JOF_ATOM", "JOF_PROP", "JOF_TYPESET"]],
    ["JSOP_SETPROP", 54, "setprop", NULL, 5, 2, 1, ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSLOPPY"]],
    ["JSOP_GETELEM", 55, "getelem", NULL, 1, 2, 1, ["JOF_BYTE", "JOF_ELEM", "JOF_TYPESET", "JOF_LEFTASSOC"]],
    ["JSOP_SETELEM", 56, "setelem", NULL, 1, 3, 1, ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSLOPPY"]],
    ["JSOP_STRICTSETELEM", 57, "strict-setelem", NULL, 1, 3, 1, ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSTRICT"]],
    ["JSOP_CALL", 58, "call", NULL, 3, -1, 1, ["JOF_UINT16", "JOF_INVOKE", "JOF_TYPESET"]],
    ["JSOP_GETNAME", 59, "getname", NULL, 5, 0, 1, ["JOF_ATOM", "JOF_NAME", "JOF_TYPESET"]],
    ["JSOP_DOUBLE", 60, "double", NULL, 5, 0, 1, ["JOF_DOUBLE"]],
    ["JSOP_STRING", 61, "string", NULL, 5, 0, 1, ["JOF_ATOM"]],
    ["JSOP_ZERO", 62, "zero", "0", 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_ONE", 63, "one", "1", 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_NULL", 64, js_null_str, js_null_str, 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_IS_CONSTRUCTING", 65, "is-constructing", NULL, 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_FALSE", 66, js_false_str, js_false_str, 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_TRUE", 67, js_true_str, js_true_str, 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_OR", 68, "or", NULL, 5, 1, 1, ["JOF_JUMP", "JOF_DETECTING", "JOF_LEFTASSOC"]],
    ["JSOP_AND", 69, "and", NULL, 5, 1, 1, ["JOF_JUMP", "JOF_DETECTING", "JOF_LEFTASSOC"]],
    ["JSOP_TABLESWITCH", 70, "tableswitch", NULL, -1, 1, 0, ["JOF_TABLESWITCH", "JOF_DETECTING"]],
    ["JSOP_RUNONCE", 71, "runonce", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_STRICTEQ", 72, "stricteq", "===", 1, 2, 1, ["JOF_BYTE", "JOF_DETECTING", "JOF_LEFTASSOC", "JOF_ARITH"]],
    ["JSOP_STRICTNE", 73, "strictne", "!==", 1, 2, 1, ["JOF_BYTE", "JOF_DETECTING", "JOF_LEFTASSOC", "JOF_ARITH"]],
    ["JSOP_THROWMSG", 74, "throwmsg", NULL, 3, 0, 0, ["JOF_UINT16"]],
    ["JSOP_ITER", 75, "iter", NULL, 2, 1, 1, ["JOF_UINT8"]],
    ["JSOP_MOREITER", 76, "moreiter", NULL, 1, 1, 2, ["JOF_BYTE"]],
    ["JSOP_ISNOITER", 77, "isnoiter", NULL, 1, 1, 2, ["JOF_BYTE"]],
    ["JSOP_ENDITER", 78, "enditer", NULL, 1, 1, 0, ["JOF_BYTE"]],
    ["JSOP_FUNAPPLY", 79, "funapply", NULL, 3, -1, 1, ["JOF_UINT16", "JOF_INVOKE", "JOF_TYPESET"]],
    ["JSOP_OBJECT", 80, "object", NULL, 5, 0, 1, ["JOF_OBJECT"]],
    ["JSOP_POP", 81, "pop", NULL, 1, 1, 0, ["JOF_BYTE"]],
    ["JSOP_NEW", 82, "new", NULL, 3, -1, 1, ["JOF_UINT16", "JOF_INVOKE", "JOF_TYPESET"]],
    ["JSOP_OBJWITHPROTO", 83, "objwithproto", NULL, 1, 1, 1, ["JOF_BYTE"]],
    ["JSOP_GETARG", 84, "getarg", NULL, 3, 0, 1, ["JOF_QARG", "JOF_NAME"]],
    ["JSOP_SETARG", 85, "setarg", NULL, 3, 1, 1, ["JOF_QARG", "JOF_NAME", "JOF_SET"]],
    ["JSOP_GETLOCAL", 86, "getlocal", NULL, 4, 0, 1, ["JOF_LOCAL", "JOF_NAME"]],
    ["JSOP_SETLOCAL", 87, "setlocal", NULL, 4, 1, 1, ["JOF_LOCAL", "JOF_NAME", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_UINT16", 88, "uint16", NULL, 3, 0, 1, ["JOF_UINT16"]],
    ["JSOP_NEWINIT", 89, "newinit", NULL, 5, 0, 1, ["JOF_UINT8"]],
    ["JSOP_NEWARRAY", 90, "newarray", NULL, 5, 0, 1, ["JOF_UINT32"]],
    ["JSOP_NEWOBJECT", 91, "newobject", NULL, 5, 0, 1, ["JOF_OBJECT"]],
    ["JSOP_INITHOMEOBJECT", 92, "inithomeobject", NULL, 2, 2, 2, ["JOF_UINT8"]],
    ["JSOP_INITPROP", 93, "initprop", NULL, 5, 2, 1, ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_INITELEM", 94, "initelem", NULL, 1, 3, 1, ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_INITELEM_INC", 95, "initelem_inc", NULL, 1, 3, 2, ["JOF_BYTE", "JOF_ELEM", "JOF_SET"]],
    ["JSOP_INITELEM_ARRAY", 96, "initelem_array", NULL, 5, 2, 1, ["JOF_UINT32", "JOF_ELEM", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_INITPROP_GETTER", 97, "initprop_getter", NULL, 5, 2, 1, ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_INITPROP_SETTER", 98, "initprop_setter", NULL, 5, 2, 1, ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_INITELEM_GETTER", 99, "initelem_getter", NULL, 1, 3, 1, ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_INITELEM_SETTER", 100, "initelem_setter", NULL, 1, 3, 1, ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_CALLSITEOBJ", 101, "callsiteobj", NULL, 5, 0, 1, ["JOF_OBJECT"]],
    ["JSOP_NEWARRAY_COPYONWRITE", 102, "newarray_copyonwrite", NULL, 5, 0, 1, ["JOF_OBJECT"]],
    ["JSOP_SUPERBASE", 103, "superbase", NULL, 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_GETPROP_SUPER", 104, "getprop-super", NULL, 5, 2, 1, ["JOF_ATOM", "JOF_PROP"]],
    ["JSOP_STRICTSETPROP_SUPER", 105, "strictsetprop-super", NULL, 5, 3, 1, ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSTRICT"]],
    ["JSOP_LABEL", 106, "label", NULL, 5, 0, 0, ["JOF_JUMP"]],
    ["JSOP_SETPROP_SUPER", 107, "setprop-super", NULL, 5, 3, 1, ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSLOPPY"]],
    ["JSOP_FUNCALL", 108, "funcall", NULL, 3, -1, 1, ["JOF_UINT16", "JOF_INVOKE", "JOF_TYPESET"]],
    ["JSOP_LOOPHEAD", 109, "loophead", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_BINDNAME", 110, "bindname", NULL, 5, 0, 1, ["JOF_ATOM", "JOF_NAME", "JOF_SET"]],
    ["JSOP_SETNAME", 111, "setname", NULL, 5, 2, 1, ["JOF_ATOM", "JOF_NAME", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSLOPPY"]],
    ["JSOP_THROW", 112, js_throw_str, NULL, 1, 1, 0, ["JOF_BYTE"]],
    ["JSOP_IN", 113, js_in_str, js_in_str, 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC"]],
    ["JSOP_INSTANCEOF", 114, js_instanceof_str, js_instanceof_str, 1, 2, 1, ["JOF_BYTE", "JOF_LEFTASSOC"]],
    ["JSOP_DEBUGGER", 115, "debugger", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_GOSUB", 116, "gosub", NULL, 5, 0, 0, ["JOF_JUMP"]],
    ["JSOP_RETSUB", 117, "retsub", NULL, 1, 2, 0, ["JOF_BYTE"]],
    ["JSOP_EXCEPTION", 118, "exception", NULL, 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_LINENO", 119, "lineno", NULL, 5, 0, 0, ["JOF_UINT32"]],
    ["JSOP_CONDSWITCH", 120, "condswitch", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_CASE", 121, "case", NULL, 5, 2, 1, ["JOF_JUMP"]],
    ["JSOP_DEFAULT", 122, "default", NULL, 5, 1, 0, ["JOF_JUMP"]],
    ["JSOP_EVAL", 123, "eval", NULL, 3, -1, 1, ["JOF_UINT16", "JOF_INVOKE", "JOF_TYPESET", "JOF_CHECKSLOPPY"]],
    ["JSOP_STRICTEVAL", 124, "strict-eval", NULL, 3, -1, 1, ["JOF_UINT16", "JOF_INVOKE", "JOF_TYPESET", "JOF_CHECKSTRICT"]],
    ["JSOP_GETELEM_SUPER", 125, "getelem-super", NULL, 1, 3, 1, ["JOF_BYTE", "JOF_ELEM", "JOF_LEFTASSOC"]],
    ["JSOP_SPREADCALLARRAY", 126, "spreadcallarray", NULL, 5, 0, 1, ["JOF_UINT32"]],
    ["JSOP_DEFFUN", 127, "deffun", NULL, 1, 1, 0, ["JOF_BYTE"]],
    ["JSOP_DEFCONST", 128, "defconst", NULL, 5, 0, 0, ["JOF_ATOM"]],
    ["JSOP_DEFVAR", 129, "defvar", NULL, 5, 0, 0, ["JOF_ATOM"]],
    ["JSOP_LAMBDA", 130, "lambda", NULL, 5, 0, 1, ["JOF_OBJECT"]],
    ["JSOP_LAMBDA_ARROW", 131, "lambda_arrow", NULL, 5, 1, 1, ["JOF_OBJECT"]],
    ["JSOP_CALLEE", 132, "callee", NULL, 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_PICK", 133, "pick", NULL, 2, 0, 0, ["JOF_UINT8"]],
    ["JSOP_TRY", 134, "try", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_FINALLY", 135, "finally", NULL, 1, 0, 2, ["JOF_BYTE"]],
    ["JSOP_GETALIASEDVAR", 136, "getaliasedvar", NULL, 5, 0, 1, ["JOF_ENVCOORD", "JOF_NAME", "JOF_TYPESET"]],
    ["JSOP_SETALIASEDVAR", 137, "setaliasedvar", NULL, 5, 1, 1, ["JOF_ENVCOORD", "JOF_NAME", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_CHECKLEXICAL", 138, "checklexical", NULL, 4, 0, 0, ["JOF_LOCAL", "JOF_NAME"]],
    ["JSOP_INITLEXICAL", 139, "initlexical", NULL, 4, 1, 1, ["JOF_LOCAL", "JOF_NAME", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_CHECKALIASEDLEXICAL", 140, "checkaliasedlexical", NULL, 5, 0, 0, ["JOF_ENVCOORD", "JOF_NAME"]],
    ["JSOP_INITALIASEDLEXICAL", 141, "initaliasedlexical", NULL, 5, 1, 1, ["JOF_ENVCOORD", "JOF_NAME", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_UNINITIALIZED", 142, "uninitialized", NULL, 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_GETINTRINSIC", 143, "getintrinsic", NULL, 5, 0, 1, ["JOF_ATOM", "JOF_NAME", "JOF_TYPESET"]],
    ["JSOP_SETINTRINSIC", 144, "setintrinsic", NULL, 5, 1, 1, ["JOF_ATOM", "JOF_NAME", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_CALLITER", 145, "calliter", NULL, 3, -1, 1, ["JOF_UINT16", "JOF_INVOKE", "JOF_TYPESET"]],
    ["JSOP_INITLOCKEDPROP", 146, "initlockedprop", NULL, 5, 2, 1, ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_INITHIDDENPROP", 147, "inithiddenprop", NULL, 5, 2, 1, ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_NEWTARGET", 148, "newtarget", NULL, 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_TOASYNC", 149, "toasync", NULL, 1, 1, 1, ["JOF_BYTE"]],
    ["JSOP_POW", 150, "pow", "**", 1, 2, 1, ["JOF_BYTE", "JOF_ARITH"]],
    ["JSOP_THROWING", 151, "throwing", NULL, 1, 1, 0, ["JOF_BYTE"]],
    ["JSOP_SETRVAL", 152, "setrval", NULL, 1, 1, 0, ["JOF_BYTE"]],
    ["JSOP_RETRVAL", 153, "retrval", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_GETGNAME", 154, "getgname", NULL, 5, 0, 1, ["JOF_ATOM", "JOF_NAME", "JOF_TYPESET", "JOF_GNAME"]],
    ["JSOP_SETGNAME", 155, "setgname", NULL, 5, 2, 1, ["JOF_ATOM", "JOF_NAME", "JOF_SET", "JOF_DETECTING", "JOF_GNAME", "JOF_CHECKSLOPPY"]],
    ["JSOP_STRICTSETGNAME", 156, "strict-setgname", NULL, 5, 2, 1, ["JOF_ATOM", "JOF_NAME", "JOF_SET", "JOF_DETECTING", "JOF_GNAME", "JOF_CHECKSTRICT"]],
    ["JSOP_GIMPLICITTHIS", 157, "gimplicitthis", "", 5, 0, 1, ["JOF_ATOM"]],
    ["JSOP_SETELEM_SUPER", 158, "setelem-super", NULL, 1, 4, 1, ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSLOPPY"]],
    ["JSOP_STRICTSETELEM_SUPER", 159, "strict-setelem-super", NULL, 1, 4, 1, ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSTRICT"]],
    ["JSOP_REGEXP", 160, "regexp", NULL, 5, 0, 1, ["JOF_REGEXP"]],
    ["JSOP_INITGLEXICAL", 161, "initglexical", NULL, 5, 1, 1, ["JOF_ATOM", "JOF_NAME", "JOF_SET", "JOF_GNAME"]],
    ["JSOP_DEFLET", 162, "deflet", NULL, 5, 0, 0, ["JOF_ATOM"]],
    ["JSOP_CHECKOBJCOERCIBLE", 163, "checkobjcoercible", NULL, 1, 1, 1, ["JOF_BYTE"]],
    ["JSOP_SUPERFUN", 164, "superfun", NULL, 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_SUPERCALL", 165, "supercall", NULL, 3, -1, 1, ["JOF_UINT16", "JOF_INVOKE", "JOF_TYPESET"]],
    ["JSOP_SPREADSUPERCALL", 166, "spreadsupercall", NULL, 1, 4, 1, ["JOF_BYTE", "JOF_INVOKE", "JOF_TYPESET"]],
    ["JSOP_CLASSCONSTRUCTOR", 167, "classconstructor", NULL, 5, 0, 1, ["JOF_ATOM"]],
    ["JSOP_DERIVEDCONSTRUCTOR", 168, "derivedconstructor", NULL, 5, 1, 1, ["JOF_ATOM"]],
    ["JSOP_THROWSETCONST", 169, "throwsetconst", NULL, 4, 1, 1, ["JOF_LOCAL", "JOF_NAME", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_THROWSETALIASEDCONST", 170, "throwsetaliasedconst", NULL, 5, 1, 1, ["JOF_ENVCOORD", "JOF_NAME", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_INITHIDDENPROP_GETTER", 171, "inithiddenprop_getter", NULL, 5, 2, 1, ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_INITHIDDENPROP_SETTER", 172, "inithiddenprop_setter", NULL, 5, 2, 1, ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_INITHIDDENELEM_GETTER", 173, "inithiddenelem_getter", NULL, 1, 3, 1, ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_INITHIDDENELEM_SETTER", 174, "inithiddenelem_setter", NULL, 1, 3, 1, ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_INITHIDDENELEM", 175, "inithiddenelem", NULL, 1, 3, 1, ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING"]],
    ["JSOP_GETIMPORT", 176, "getimport", NULL, 5, 0, 1, ["JOF_ATOM", "JOF_NAME", "JOF_TYPESET"]],
    ["JSOP_DEBUGCHECKSELFHOSTED", 177, "debug-checkselfhosted", NULL, 1, 1, 1, ["JOF_BYTE"]],
    ["JSOP_OPTIMIZE_SPREADCALL", 178, "optimize-spreadcall", NULL, 1, 1, 2, ["JOF_BYTE"]],
    ["JSOP_THROWSETCALLEE", 179, "throwsetcallee", NULL, 1, 1, 1, ["JOF_SET", "JOF_BYTE"]],
    ["JSOP_PUSHVARENV", 180, "pushvarenv", NULL, 5, 0, 0, ["JOF_SCOPE"]],
    ["JSOP_POPVARENV", 181, "popvarenv", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_UNUSED182", 182, "unused182", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_UNUSED183", 183, "unused183", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_CALLPROP", 184, "callprop", NULL, 5, 1, 1, ["JOF_ATOM", "JOF_PROP", "JOF_TYPESET"]],
    ["JSOP_FUNCTIONTHIS", 185, "functionthis", NULL, 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_GLOBALTHIS", 186, "globalthis", NULL, 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_UNUSED187", 187, "unused187", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_UINT24", 188, "uint24", NULL, 4, 0, 1, ["JOF_UINT24"]],
    ["JSOP_CHECKTHIS", 189, "checkthis", NULL, 1, 1, 1, ["JOF_BYTE"]],
    ["JSOP_CHECKRETURN", 190, "checkreturn", NULL, 1, 1, 0, ["JOF_BYTE"]],
    ["JSOP_CHECKTHISREINIT", 191, "checkthisreinit", NULL, 1, 1, 1, ["JOF_BYTE"]],
    ["JSOP_UNUSED192", 192, "unused192", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_CALLELEM", 193, "callelem", NULL, 1, 2, 1, ["JOF_BYTE", "JOF_ELEM", "JOF_TYPESET", "JOF_LEFTASSOC"]],
    ["JSOP_MUTATEPROTO", 194, "mutateproto", NULL, 1, 2, 1, ["JOF_BYTE"]],
    ["JSOP_GETXPROP", 195, "getxprop", NULL, 5, 1, 1, ["JOF_ATOM", "JOF_PROP", "JOF_TYPESET"]],
    ["JSOP_TYPEOFEXPR", 196, "typeofexpr", NULL, 1, 1, 1, ["JOF_BYTE", "JOF_DETECTING"]],
    ["JSOP_FRESHENLEXICALENV", 197, "freshenlexicalenv", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_RECREATELEXICALENV", 198, "recreatelexicalenv", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_PUSHLEXICALENV", 199, "pushlexicalenv", NULL, 5, 0, 0, ["JOF_SCOPE"]],
    ["JSOP_POPLEXICALENV", 200, "poplexicalenv", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_DEBUGLEAVELEXICALENV", 201, "debugleavelexicalenv", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_INITIALYIELD", 202, "initialyield", NULL, 4, 1, 1, ["JOF_UINT24"]],
    ["JSOP_YIELD", 203, "yield", NULL, 4, 2, 1, ["JOF_UINT24"]],
    ["JSOP_FINALYIELDRVAL", 204, "finalyieldrval", NULL, 1, 1, 0, ["JOF_BYTE"]],
    ["JSOP_RESUME", 205, "resume", NULL, 3, 2, 1, ["JOF_UINT8", "JOF_INVOKE"]],
    ["JSOP_ARRAYPUSH", 206, "arraypush", NULL, 1, 2, 0, ["JOF_BYTE"]],
    ["JSOP_FORCEINTERPRETER", 207, "forceinterpreter", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_DEBUGAFTERYIELD", 208, "debugafteryield", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_UNUSED209", 209, "unused209", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_UNUSED210", 210, "unused210", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_UNUSED211", 211, "unused211", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_GENERATOR", 212, "generator", NULL, 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_BINDVAR", 213, "bindvar", NULL, 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_BINDGNAME", 214, "bindgname", NULL, 5, 0, 1, ["JOF_ATOM", "JOF_NAME", "JOF_SET", "JOF_GNAME"]],
    ["JSOP_INT8", 215, "int8", NULL, 2, 0, 1, ["JOF_INT8"]],
    ["JSOP_INT32", 216, "int32", NULL, 5, 0, 1, ["JOF_INT32"]],
    ["JSOP_LENGTH", 217, "length", NULL, 5, 1, 1, ["JOF_ATOM", "JOF_PROP", "JOF_TYPESET"]],
    ["JSOP_HOLE", 218, "hole", NULL, 1, 0, 1, ["JOF_BYTE"]],
    ["JSOP_UNUSED219", 219, "unused219", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_UNUSED220", 220, "unused220", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_UNUSED221", 221, "unused221", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_UNUSED222", 222, "unused222", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_UNUSED223", 223, "unused223", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_REST", 224, "rest", NULL, 1, 0, 1, ["JOF_BYTE", "JOF_TYPESET"]],
    ["JSOP_TOID", 225, "toid", NULL, 1, 1, 1, ["JOF_BYTE"]],
    ["JSOP_IMPLICITTHIS", 226, "implicitthis", "", 5, 0, 1, ["JOF_ATOM"]],
    ["JSOP_LOOPENTRY", 227, "loopentry", NULL, 2, 0, 0, ["JOF_UINT8"]],
    ["JSOP_TOSTRING", 228, "tostring", NULL, 1, 1, 1, ["JOF_BYTE"]],
    ["JSOP_NOP_DESTRUCTURING", 229, "nop-destructuring", NULL, 1, 0, 0, ["JOF_BYTE"]],
    ["JSOP_JUMPTARGET", 230, "jumptarget", NULL, 1, 0, 0, ["JOF_BYTE"]],
];
$outputs = [];
foreach ($opcodes as $opcode) {
    $outputs[$opcode[1]] = [
        'op' => $opcode[0],
        'val' => $opcode[1],
        'name' => $opcode[2],
        'image' => $opcode[3],
        'len' => $opcode[4],
        'use' => $opcode[5],
        'def' => $opcode[6],
        'format' => $opcode[7],
    ];
}
file_put_contents("./Opcode.php", serialize($outputs));

