<?php

/**
 * Created by PhpStorm.
 * User: irelance
 * Date: 2017/9/30
 * Time: 上午10:05
 */
namespace Irelance\Mozjs52;

define("js_undefined_str", "__undefined__");
define("js_typeof_str", "__typeof__");
define("js_void_str", "__void__");
define("js_null_str", "__null__");
define("js_false_str", "__false__");
define("js_true_str", "__true__");
define("js_throw_str", "__throw__");
define("js_in_str", "__in__");
define("js_instanceof_str", "__instanceof__");

class Constant
{
    const _Scope = [
        // FunctionScope
        'Function',
        // VarScope
        'FunctionBodyVar', 'ParameterExpressionVar',
        // LexicalScope
        'Lexical', 'SimpleCatch', 'Catch', 'NamedLambda', 'StrictNamedLambda',
        // WithScope
        'With',
        // EvalScope
        'Eval', 'StrictEval',
        // GlobalScope
        'Global', 'NonSyntactic',
        // ModuleScope
        'Module'
    ];

    const _ConstTag = [
        'SCRIPT_INT',
        'SCRIPT_DOUBLE',
        'SCRIPT_ATOM',
        'SCRIPT_TRUE',
        'SCRIPT_FALSE',
        'SCRIPT_NULL',
        'SCRIPT_OBJECT',
        'SCRIPT_VOID',
        'SCRIPT_HOLE',
    ];

    const _Class = [
        'CK_RegexpObject',//正则表达式
        'CK_JSFunction',
        'CK_JSObject'
    ];

    const _ScriptBits = [
        'NoScriptRval',
        'Strict',
        'ContainsDynamicNameAccess',
        'FunHasExtensibleScope',
        'FunHasAnyAliasedFormal',
        'ArgumentsHasVarBinding',
        'NeedsArgsObj',
        'HasMappedArgsObj',
        'FunctionHasThisBinding',
        'FunctionHasExtraBodyVarScope',
        'IsGeneratorExp',
        'IsLegacyGenerator',
        'IsStarGenerator',
        'IsAsync',
        'OwnSource',
        'ExplicitUseStrict',
        'SelfHosted',
        'HasSingleton',
        'TreatAsRunOnce',
        'HasLazyScript',
        'HasNonSyntacticScope',
        'HasInnerFunctions',
        'NeedsHomeObject',
        'IsDerivedClassConstructor',
        'IsDefaultClassConstructor',
    ];

    const _FirstWordFlag = [
        'HasAtom' => 0x1,
        'IsStarGenerator' => 0x2,
        'IsLazy' => 0x4,
        'HasSingletonType' => 0x8
    ];

    const _Opcode = [
        0 => ['op' => "JSOP_NOP", 'val' => 0, 'name' => "nop", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        1 => ['op' => "JSOP_UNDEFINED", 'val' => 1, 'name' => js_undefined_str, 'image' => "", 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        2 => ['op' => "JSOP_GETRVAL", 'val' => 2, 'name' => "getrval", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        3 => ['op' => "JSOP_ENTERWITH", 'val' => 3, 'name' => "enterwith", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 0, 'format' => ["JOF_SCOPE"]],
        4 => ['op' => "JSOP_LEAVEWITH", 'val' => 4, 'name' => "leavewith", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        5 => ['op' => "JSOP_RETURN", 'val' => 5, 'name' => "return", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 0, 'format' => ["JOF_BYTE"]],
        6 => ['op' => "JSOP_GOTO", 'val' => 6, 'name' => "goto", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ["JOF_JUMP"]],
        7 => ['op' => "JSOP_IFEQ", 'val' => 7, 'name' => "ifeq", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 0, 'format' => ["JOF_JUMP", "JOF_DETECTING"]],
        8 => ['op' => "JSOP_IFNE", 'val' => 8, 'name' => "ifne", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 0, 'format' => ["JOF_JUMP"]],
        9 => ['op' => "JSOP_ARGUMENTS", 'val' => 9, 'name' => "arguments", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        10 => ['op' => "JSOP_SWAP", 'val' => 10, 'name' => "swap", 'image' => NULL, 'len' => 1, 'use' => 2, 'def' => 2, 'format' => ["JOF_BYTE"]],
        11 => ['op' => "JSOP_POPN", 'val' => 11, 'name' => "popn", 'image' => NULL, 'len' => 3, 'use' => -1, 'def' => 0, 'format' => ["JOF_UINT16"]],
        12 => ['op' => "JSOP_DUP", 'val' => 12, 'name' => "dup", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 2, 'format' => ["JOF_BYTE"]],
        13 => ['op' => "JSOP_DUP2", 'val' => 13, 'name' => "dup2", 'image' => NULL, 'len' => 1, 'use' => 2, 'def' => 4, 'format' => ["JOF_BYTE"]],
        14 => ['op' => "JSOP_CHECKISOBJ", 'val' => 14, 'name' => "checkisobj", 'image' => NULL, 'len' => 2, 'use' => 1, 'def' => 1, 'format' => ["JOF_UINT8"]],
        15 => ['op' => "JSOP_BITOR", 'val' => 15, 'name' => "bitor", 'image' => "|", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
        16 => ['op' => "JSOP_BITXOR", 'val' => 16, 'name' => "bitxor", 'image' => "^", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
        17 => ['op' => "JSOP_BITAND", 'val' => 17, 'name' => "bitand", 'image' => "&", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
        18 => ['op' => "JSOP_EQ", 'val' => 18, 'name' => "eq", 'image' => "==", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH", "JOF_DETECTING"]],
        19 => ['op' => "JSOP_NE", 'val' => 19, 'name' => "ne", 'image' => "!=", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH", "JOF_DETECTING"]],
        20 => ['op' => "JSOP_LT", 'val' => 20, 'name' => "lt", 'image' => "<", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
        21 => ['op' => "JSOP_LE", 'val' => 21, 'name' => "le", 'image' => "<=", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
        22 => ['op' => "JSOP_GT", 'val' => 22, 'name' => "gt", 'image' => ">", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
        23 => ['op' => "JSOP_GE", 'val' => 23, 'name' => "ge", 'image' => ">=", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
        24 => ['op' => "JSOP_LSH", 'val' => 24, 'name' => "lsh", 'image' => "<<", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
        25 => ['op' => "JSOP_RSH", 'val' => 25, 'name' => "rsh", 'image' => ">>", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
        26 => ['op' => "JSOP_URSH", 'val' => 26, 'name' => "ursh", 'image' => ">>>", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
        27 => ['op' => "JSOP_ADD", 'val' => 27, 'name' => "add", 'image' => "+", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
        28 => ['op' => "JSOP_SUB", 'val' => 28, 'name' => "sub", 'image' => "-", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
        29 => ['op' => "JSOP_MUL", 'val' => 29, 'name' => "mul", 'image' => "*", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
        30 => ['op' => "JSOP_DIV", 'val' => 30, 'name' => "div", 'image' => "/", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
        31 => ['op' => "JSOP_MOD", 'val' => 31, 'name' => "mod", 'image' => "%", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC", "JOF_ARITH"]],
        32 => ['op' => "JSOP_NOT", 'val' => 32, 'name' => "not", 'image' => "!", 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ARITH", "JOF_DETECTING"]],
        33 => ['op' => "JSOP_BITNOT", 'val' => 33, 'name' => "bitnot", 'image' => "~", 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ARITH"]],
        34 => ['op' => "JSOP_NEG", 'val' => 34, 'name' => "neg", 'image' => "- ", 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ARITH"]],
        35 => ['op' => "JSOP_POS", 'val' => 35, 'name' => "pos", 'image' => "+ ", 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ARITH"]],
        36 => ['op' => "JSOP_DELNAME", 'val' => 36, 'name' => "delname", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_NAME", "JOF_CHECKSLOPPY"]],
        37 => ['op' => "JSOP_DELPROP", 'val' => 37, 'name' => "delprop", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP", "JOF_CHECKSLOPPY"]],
        38 => ['op' => "JSOP_DELELEM", 'val' => 38, 'name' => "delelem", 'image' => NULL, 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ELEM", "JOF_CHECKSLOPPY"]],
        39 => ['op' => "JSOP_TYPEOF", 'val' => 39, 'name' => js_typeof_str, 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_DETECTING"]],
        40 => ['op' => "JSOP_VOID", 'val' => 40, 'name' => js_void_str, 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ["JOF_BYTE"]],
        41 => ['op' => "JSOP_SPREADCALL", 'val' => 41, 'name' => "spreadcall", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_INVOKE", "JOF_TYPESET"]],
        42 => ['op' => "JSOP_SPREADNEW", 'val' => 42, 'name' => "spreadnew", 'image' => NULL, 'len' => 1, 'use' => 4, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_INVOKE", "JOF_TYPESET"]],
        43 => ['op' => "JSOP_SPREADEVAL", 'val' => 43, 'name' => "spreadeval", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_INVOKE", "JOF_TYPESET", "JOF_CHECKSLOPPY"]],
        44 => ['op' => "JSOP_DUPAT", 'val' => 44, 'name' => "dupat", 'image' => NULL, 'len' => 4, 'use' => 0, 'def' => 1, 'format' => ["JOF_UINT24"]],
        45 => ['op' => "JSOP_SYMBOL", 'val' => 45, 'name' => "symbol", 'image' => NULL, 'len' => 2, 'use' => 0, 'def' => 1, 'format' => ["JOF_UINT8"]],
        46 => ['op' => "JSOP_STRICTDELPROP", 'val' => 46, 'name' => "strict-delprop", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP", "JOF_CHECKSTRICT"]],
        47 => ['op' => "JSOP_STRICTDELELEM", 'val' => 47, 'name' => "strict-delelem", 'image' => NULL, 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ELEM", "JOF_CHECKSTRICT"]],
        48 => ['op' => "JSOP_STRICTSETPROP", 'val' => 48, 'name' => "strict-setprop", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSTRICT"]],
        49 => ['op' => "JSOP_STRICTSETNAME", 'val' => 49, 'name' => "strict-setname", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_NAME", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSTRICT"]],
        50 => ['op' => "JSOP_STRICTSPREADEVAL", 'val' => 50, 'name' => "strict-spreadeval", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_INVOKE", "JOF_TYPESET", "JOF_CHECKSTRICT"]],
        51 => ['op' => "JSOP_CLASSHERITAGE", 'val' => 51, 'name' => "classheritage", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 2, 'format' => ["JOF_BYTE"]],
        52 => ['op' => "JSOP_FUNWITHPROTO", 'val' => 52, 'name' => "funwithproto", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ["JOF_OBJECT"]],
        53 => ['op' => "JSOP_GETPROP", 'val' => 53, 'name' => "getprop", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP", "JOF_TYPESET"]],
        54 => ['op' => "JSOP_SETPROP", 'val' => 54, 'name' => "setprop", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSLOPPY"]],
        55 => ['op' => "JSOP_GETELEM", 'val' => 55, 'name' => "getelem", 'image' => NULL, 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ELEM", "JOF_TYPESET", "JOF_LEFTASSOC"]],
        56 => ['op' => "JSOP_SETELEM", 'val' => 56, 'name' => "setelem", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSLOPPY"]],
        57 => ['op' => "JSOP_STRICTSETELEM", 'val' => 57, 'name' => "strict-setelem", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSTRICT"]],
        58 => ['op' => "JSOP_CALL", 'val' => 58, 'name' => "call", 'image' => NULL, 'len' => 3, 'use' => -1, 'def' => 1, 'format' => ["JOF_UINT16", "JOF_INVOKE", "JOF_TYPESET"]],
        59 => ['op' => "JSOP_GETNAME", 'val' => 59, 'name' => "getname", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_NAME", "JOF_TYPESET"]],
        60 => ['op' => "JSOP_DOUBLE", 'val' => 60, 'name' => "double", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_DOUBLE"]],
        61 => ['op' => "JSOP_STRING", 'val' => 61, 'name' => "string", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_ATOM"]],
        62 => ['op' => "JSOP_ZERO", 'val' => 62, 'name' => "zero", 'image' => "0", 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        63 => ['op' => "JSOP_ONE", 'val' => 63, 'name' => "one", 'image' => "1", 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        64 => ['op' => "JSOP_NULL", 'val' => 64, 'name' => js_null_str, 'image' => js_null_str, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        65 => ['op' => "JSOP_IS_CONSTRUCTING", 'val' => 65, 'name' => "is-constructing", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        66 => ['op' => "JSOP_FALSE", 'val' => 66, 'name' => js_false_str, 'image' => js_false_str, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        67 => ['op' => "JSOP_TRUE", 'val' => 67, 'name' => js_true_str, 'image' => js_true_str, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        68 => ['op' => "JSOP_OR", 'val' => 68, 'name' => "or", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ["JOF_JUMP", "JOF_DETECTING", "JOF_LEFTASSOC"]],
        69 => ['op' => "JSOP_AND", 'val' => 69, 'name' => "and", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ["JOF_JUMP", "JOF_DETECTING", "JOF_LEFTASSOC"]],
        70 => ['op' => "JSOP_TABLESWITCH", 'val' => 70, 'name' => "tableswitch", 'image' => NULL, 'len' => -1, 'use' => 1, 'def' => 0, 'format' => ["JOF_TABLESWITCH", "JOF_DETECTING"]],
        71 => ['op' => "JSOP_RUNONCE", 'val' => 71, 'name' => "runonce", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        72 => ['op' => "JSOP_STRICTEQ", 'val' => 72, 'name' => "stricteq", 'image' => "===", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_DETECTING", "JOF_LEFTASSOC", "JOF_ARITH"]],
        73 => ['op' => "JSOP_STRICTNE", 'val' => 73, 'name' => "strictne", 'image' => "!==", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_DETECTING", "JOF_LEFTASSOC", "JOF_ARITH"]],
        74 => ['op' => "JSOP_THROWMSG", 'val' => 74, 'name' => "throwmsg", 'image' => NULL, 'len' => 3, 'use' => 0, 'def' => 0, 'format' => ["JOF_UINT16"]],
        75 => ['op' => "JSOP_ITER", 'val' => 75, 'name' => "iter", 'image' => NULL, 'len' => 2, 'use' => 1, 'def' => 1, 'format' => ["JOF_UINT8"]],
        76 => ['op' => "JSOP_MOREITER", 'val' => 76, 'name' => "moreiter", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 2, 'format' => ["JOF_BYTE"]],
        77 => ['op' => "JSOP_ISNOITER", 'val' => 77, 'name' => "isnoiter", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 2, 'format' => ["JOF_BYTE"]],
        78 => ['op' => "JSOP_ENDITER", 'val' => 78, 'name' => "enditer", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 0, 'format' => ["JOF_BYTE"]],
        79 => ['op' => "JSOP_FUNAPPLY", 'val' => 79, 'name' => "funapply", 'image' => NULL, 'len' => 3, 'use' => -1, 'def' => 1, 'format' => ["JOF_UINT16", "JOF_INVOKE", "JOF_TYPESET"]],
        80 => ['op' => "JSOP_OBJECT", 'val' => 80, 'name' => "object", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_OBJECT"]],
        81 => ['op' => "JSOP_POP", 'val' => 81, 'name' => "pop", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 0, 'format' => ["JOF_BYTE"]],
        82 => ['op' => "JSOP_NEW", 'val' => 82, 'name' => "new", 'image' => NULL, 'len' => 3, 'use' => -1, 'def' => 1, 'format' => ["JOF_UINT16", "JOF_INVOKE", "JOF_TYPESET"]],
        83 => ['op' => "JSOP_OBJWITHPROTO", 'val' => 83, 'name' => "objwithproto", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ["JOF_BYTE"]],
        84 => ['op' => "JSOP_GETARG", 'val' => 84, 'name' => "getarg", 'image' => NULL, 'len' => 3, 'use' => 0, 'def' => 1, 'format' => ["JOF_QARG", "JOF_NAME"]],
        85 => ['op' => "JSOP_SETARG", 'val' => 85, 'name' => "setarg", 'image' => NULL, 'len' => 3, 'use' => 1, 'def' => 1, 'format' => ["JOF_QARG", "JOF_NAME", "JOF_SET"]],
        86 => ['op' => "JSOP_GETLOCAL", 'val' => 86, 'name' => "getlocal", 'image' => NULL, 'len' => 4, 'use' => 0, 'def' => 1, 'format' => ["JOF_LOCAL", "JOF_NAME"]],
        87 => ['op' => "JSOP_SETLOCAL", 'val' => 87, 'name' => "setlocal", 'image' => NULL, 'len' => 4, 'use' => 1, 'def' => 1, 'format' => ["JOF_LOCAL", "JOF_NAME", "JOF_SET", "JOF_DETECTING"]],
        88 => ['op' => "JSOP_UINT16", 'val' => 88, 'name' => "uint16", 'image' => NULL, 'len' => 3, 'use' => 0, 'def' => 1, 'format' => ["JOF_UINT16"]],
        89 => ['op' => "JSOP_NEWINIT", 'val' => 89, 'name' => "newinit", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_UINT8"]],
        90 => ['op' => "JSOP_NEWARRAY", 'val' => 90, 'name' => "newarray", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_UINT32"]],
        91 => ['op' => "JSOP_NEWOBJECT", 'val' => 91, 'name' => "newobject", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_OBJECT"]],
        92 => ['op' => "JSOP_INITHOMEOBJECT", 'val' => 92, 'name' => "inithomeobject", 'image' => NULL, 'len' => 2, 'use' => 2, 'def' => 2, 'format' => ["JOF_UINT8"]],
        93 => ['op' => "JSOP_INITPROP", 'val' => 93, 'name' => "initprop", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING"]],
        94 => ['op' => "JSOP_INITELEM", 'val' => 94, 'name' => "initelem", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING"]],
        95 => ['op' => "JSOP_INITELEM_INC", 'val' => 95, 'name' => "initelem_inc", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 2, 'format' => ["JOF_BYTE", "JOF_ELEM", "JOF_SET"]],
        96 => ['op' => "JSOP_INITELEM_ARRAY", 'val' => 96, 'name' => "initelem_array", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ["JOF_UINT32", "JOF_ELEM", "JOF_SET", "JOF_DETECTING"]],
        97 => ['op' => "JSOP_INITPROP_GETTER", 'val' => 97, 'name' => "initprop_getter", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING"]],
        98 => ['op' => "JSOP_INITPROP_SETTER", 'val' => 98, 'name' => "initprop_setter", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING"]],
        99 => ['op' => "JSOP_INITELEM_GETTER", 'val' => 99, 'name' => "initelem_getter", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING"]],
        100 => ['op' => "JSOP_INITELEM_SETTER", 'val' => 100, 'name' => "initelem_setter", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING"]],
        101 => ['op' => "JSOP_CALLSITEOBJ", 'val' => 101, 'name' => "callsiteobj", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_OBJECT"]],
        102 => ['op' => "JSOP_NEWARRAY_COPYONWRITE", 'val' => 102, 'name' => "newarray_copyonwrite", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_OBJECT"]],
        103 => ['op' => "JSOP_SUPERBASE", 'val' => 103, 'name' => "superbase", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        104 => ['op' => "JSOP_GETPROP_SUPER", 'val' => 104, 'name' => "getprop-super", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP"]],
        105 => ['op' => "JSOP_STRICTSETPROP_SUPER", 'val' => 105, 'name' => "strictsetprop-super", 'image' => NULL, 'len' => 5, 'use' => 3, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSTRICT"]],
        106 => ['op' => "JSOP_LABEL", 'val' => 106, 'name' => "label", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ["JOF_JUMP"]],
        107 => ['op' => "JSOP_SETPROP_SUPER", 'val' => 107, 'name' => "setprop-super", 'image' => NULL, 'len' => 5, 'use' => 3, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSLOPPY"]],
        108 => ['op' => "JSOP_FUNCALL", 'val' => 108, 'name' => "funcall", 'image' => NULL, 'len' => 3, 'use' => -1, 'def' => 1, 'format' => ["JOF_UINT16", "JOF_INVOKE", "JOF_TYPESET"]],
        109 => ['op' => "JSOP_LOOPHEAD", 'val' => 109, 'name' => "loophead", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        110 => ['op' => "JSOP_BINDNAME", 'val' => 110, 'name' => "bindname", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_NAME", "JOF_SET"]],
        111 => ['op' => "JSOP_SETNAME", 'val' => 111, 'name' => "setname", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_NAME", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSLOPPY"]],
        112 => ['op' => "JSOP_THROW", 'val' => 112, 'name' => js_throw_str, 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 0, 'format' => ["JOF_BYTE"]],
        113 => ['op' => "JSOP_IN", 'val' => 113, 'name' => js_in_str, 'image' => js_in_str, 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC"]],
        114 => ['op' => "JSOP_INSTANCEOF", 'val' => 114, 'name' => js_instanceof_str, 'image' => js_instanceof_str, 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_LEFTASSOC"]],
        115 => ['op' => "JSOP_DEBUGGER", 'val' => 115, 'name' => "debugger", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        116 => ['op' => "JSOP_GOSUB", 'val' => 116, 'name' => "gosub", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ["JOF_JUMP"]],
        117 => ['op' => "JSOP_RETSUB", 'val' => 117, 'name' => "retsub", 'image' => NULL, 'len' => 1, 'use' => 2, 'def' => 0, 'format' => ["JOF_BYTE"]],
        118 => ['op' => "JSOP_EXCEPTION", 'val' => 118, 'name' => "exception", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        119 => ['op' => "JSOP_LINENO", 'val' => 119, 'name' => "lineno", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ["JOF_UINT32"]],
        120 => ['op' => "JSOP_CONDSWITCH", 'val' => 120, 'name' => "condswitch", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        121 => ['op' => "JSOP_CASE", 'val' => 121, 'name' => "case", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ["JOF_JUMP"]],
        122 => ['op' => "JSOP_DEFAULT", 'val' => 122, 'name' => "default", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 0, 'format' => ["JOF_JUMP"]],
        123 => ['op' => "JSOP_EVAL", 'val' => 123, 'name' => "eval", 'image' => NULL, 'len' => 3, 'use' => -1, 'def' => 1, 'format' => ["JOF_UINT16", "JOF_INVOKE", "JOF_TYPESET", "JOF_CHECKSLOPPY"]],
        124 => ['op' => "JSOP_STRICTEVAL", 'val' => 124, 'name' => "strict-eval", 'image' => NULL, 'len' => 3, 'use' => -1, 'def' => 1, 'format' => ["JOF_UINT16", "JOF_INVOKE", "JOF_TYPESET", "JOF_CHECKSTRICT"]],
        125 => ['op' => "JSOP_GETELEM_SUPER", 'val' => 125, 'name' => "getelem-super", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ELEM", "JOF_LEFTASSOC"]],
        126 => ['op' => "JSOP_SPREADCALLARRAY", 'val' => 126, 'name' => "spreadcallarray", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_UINT32"]],
        127 => ['op' => "JSOP_DEFFUN", 'val' => 127, 'name' => "deffun", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 0, 'format' => ["JOF_BYTE"]],
        128 => ['op' => "JSOP_DEFCONST", 'val' => 128, 'name' => "defconst", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ["JOF_ATOM"]],
        129 => ['op' => "JSOP_DEFVAR", 'val' => 129, 'name' => "defvar", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ["JOF_ATOM"]],
        130 => ['op' => "JSOP_LAMBDA", 'val' => 130, 'name' => "lambda", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_OBJECT"]],
        131 => ['op' => "JSOP_LAMBDA_ARROW", 'val' => 131, 'name' => "lambda_arrow", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ["JOF_OBJECT"]],
        132 => ['op' => "JSOP_CALLEE", 'val' => 132, 'name' => "callee", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        133 => ['op' => "JSOP_PICK", 'val' => 133, 'name' => "pick", 'image' => NULL, 'len' => 2, 'use' => 0, 'def' => 0, 'format' => ["JOF_UINT8"]],
        134 => ['op' => "JSOP_TRY", 'val' => 134, 'name' => "try", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        135 => ['op' => "JSOP_FINALLY", 'val' => 135, 'name' => "finally", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 2, 'format' => ["JOF_BYTE"]],
        136 => ['op' => "JSOP_GETALIASEDVAR", 'val' => 136, 'name' => "getaliasedvar", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_ENVCOORD", "JOF_NAME", "JOF_TYPESET"]],
        137 => ['op' => "JSOP_SETALIASEDVAR", 'val' => 137, 'name' => "setaliasedvar", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ["JOF_ENVCOORD", "JOF_NAME", "JOF_SET", "JOF_DETECTING"]],
        138 => ['op' => "JSOP_CHECKLEXICAL", 'val' => 138, 'name' => "checklexical", 'image' => NULL, 'len' => 4, 'use' => 0, 'def' => 0, 'format' => ["JOF_LOCAL", "JOF_NAME"]],
        139 => ['op' => "JSOP_INITLEXICAL", 'val' => 139, 'name' => "initlexical", 'image' => NULL, 'len' => 4, 'use' => 1, 'def' => 1, 'format' => ["JOF_LOCAL", "JOF_NAME", "JOF_SET", "JOF_DETECTING"]],
        140 => ['op' => "JSOP_CHECKALIASEDLEXICAL", 'val' => 140, 'name' => "checkaliasedlexical", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ["JOF_ENVCOORD", "JOF_NAME"]],
        141 => ['op' => "JSOP_INITALIASEDLEXICAL", 'val' => 141, 'name' => "initaliasedlexical", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ["JOF_ENVCOORD", "JOF_NAME", "JOF_SET", "JOF_DETECTING"]],
        142 => ['op' => "JSOP_UNINITIALIZED", 'val' => 142, 'name' => "uninitialized", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        143 => ['op' => "JSOP_GETINTRINSIC", 'val' => 143, 'name' => "getintrinsic", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_NAME", "JOF_TYPESET"]],
        144 => ['op' => "JSOP_SETINTRINSIC", 'val' => 144, 'name' => "setintrinsic", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_NAME", "JOF_SET", "JOF_DETECTING"]],
        145 => ['op' => "JSOP_CALLITER", 'val' => 145, 'name' => "calliter", 'image' => NULL, 'len' => 3, 'use' => -1, 'def' => 1, 'format' => ["JOF_UINT16", "JOF_INVOKE", "JOF_TYPESET"]],
        146 => ['op' => "JSOP_INITLOCKEDPROP", 'val' => 146, 'name' => "initlockedprop", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING"]],
        147 => ['op' => "JSOP_INITHIDDENPROP", 'val' => 147, 'name' => "inithiddenprop", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING"]],
        148 => ['op' => "JSOP_NEWTARGET", 'val' => 148, 'name' => "newtarget", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        149 => ['op' => "JSOP_TOASYNC", 'val' => 149, 'name' => "toasync", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ["JOF_BYTE"]],
        150 => ['op' => "JSOP_POW", 'val' => 150, 'name' => "pow", 'image' => "**", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ARITH"]],
        151 => ['op' => "JSOP_THROWING", 'val' => 151, 'name' => "throwing", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 0, 'format' => ["JOF_BYTE"]],
        152 => ['op' => "JSOP_SETRVAL", 'val' => 152, 'name' => "setrval", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 0, 'format' => ["JOF_BYTE"]],
        153 => ['op' => "JSOP_RETRVAL", 'val' => 153, 'name' => "retrval", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        154 => ['op' => "JSOP_GETGNAME", 'val' => 154, 'name' => "getgname", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_NAME", "JOF_TYPESET", "JOF_GNAME"]],
        155 => ['op' => "JSOP_SETGNAME", 'val' => 155, 'name' => "setgname", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_NAME", "JOF_SET", "JOF_DETECTING", "JOF_GNAME", "JOF_CHECKSLOPPY"]],
        156 => ['op' => "JSOP_STRICTSETGNAME", 'val' => 156, 'name' => "strict-setgname", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_NAME", "JOF_SET", "JOF_DETECTING", "JOF_GNAME", "JOF_CHECKSTRICT"]],
        157 => ['op' => "JSOP_GIMPLICITTHIS", 'val' => 157, 'name' => "gimplicitthis", 'image' => "", 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_ATOM"]],
        158 => ['op' => "JSOP_SETELEM_SUPER", 'val' => 158, 'name' => "setelem-super", 'image' => NULL, 'len' => 1, 'use' => 4, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSLOPPY"]],
        159 => ['op' => "JSOP_STRICTSETELEM_SUPER", 'val' => 159, 'name' => "strict-setelem-super", 'image' => NULL, 'len' => 1, 'use' => 4, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING", "JOF_CHECKSTRICT"]],
        160 => ['op' => "JSOP_REGEXP", 'val' => 160, 'name' => "regexp", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_REGEXP"]],
        161 => ['op' => "JSOP_INITGLEXICAL", 'val' => 161, 'name' => "initglexical", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_NAME", "JOF_SET", "JOF_GNAME"]],
        162 => ['op' => "JSOP_DEFLET", 'val' => 162, 'name' => "deflet", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ["JOF_ATOM"]],
        163 => ['op' => "JSOP_CHECKOBJCOERCIBLE", 'val' => 163, 'name' => "checkobjcoercible", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ["JOF_BYTE"]],
        164 => ['op' => "JSOP_SUPERFUN", 'val' => 164, 'name' => "superfun", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        165 => ['op' => "JSOP_SUPERCALL", 'val' => 165, 'name' => "supercall", 'image' => NULL, 'len' => 3, 'use' => -1, 'def' => 1, 'format' => ["JOF_UINT16", "JOF_INVOKE", "JOF_TYPESET"]],
        166 => ['op' => "JSOP_SPREADSUPERCALL", 'val' => 166, 'name' => "spreadsupercall", 'image' => NULL, 'len' => 1, 'use' => 4, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_INVOKE", "JOF_TYPESET"]],
        167 => ['op' => "JSOP_CLASSCONSTRUCTOR", 'val' => 167, 'name' => "classconstructor", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_ATOM"]],
        168 => ['op' => "JSOP_DERIVEDCONSTRUCTOR", 'val' => 168, 'name' => "derivedconstructor", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ["JOF_ATOM"]],
        169 => ['op' => "JSOP_THROWSETCONST", 'val' => 169, 'name' => "throwsetconst", 'image' => NULL, 'len' => 4, 'use' => 1, 'def' => 1, 'format' => ["JOF_LOCAL", "JOF_NAME", "JOF_SET", "JOF_DETECTING"]],
        170 => ['op' => "JSOP_THROWSETALIASEDCONST", 'val' => 170, 'name' => "throwsetaliasedconst", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ["JOF_ENVCOORD", "JOF_NAME", "JOF_SET", "JOF_DETECTING"]],
        171 => ['op' => "JSOP_INITHIDDENPROP_GETTER", 'val' => 171, 'name' => "inithiddenprop_getter", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING"]],
        172 => ['op' => "JSOP_INITHIDDENPROP_SETTER", 'val' => 172, 'name' => "inithiddenprop_setter", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP", "JOF_SET", "JOF_DETECTING"]],
        173 => ['op' => "JSOP_INITHIDDENELEM_GETTER", 'val' => 173, 'name' => "inithiddenelem_getter", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING"]],
        174 => ['op' => "JSOP_INITHIDDENELEM_SETTER", 'val' => 174, 'name' => "inithiddenelem_setter", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING"]],
        175 => ['op' => "JSOP_INITHIDDENELEM", 'val' => 175, 'name' => "inithiddenelem", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ELEM", "JOF_SET", "JOF_DETECTING"]],
        176 => ['op' => "JSOP_GETIMPORT", 'val' => 176, 'name' => "getimport", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_NAME", "JOF_TYPESET"]],
        177 => ['op' => "JSOP_DEBUGCHECKSELFHOSTED", 'val' => 177, 'name' => "debug-checkselfhosted", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ["JOF_BYTE"]],
        178 => ['op' => "JSOP_OPTIMIZE_SPREADCALL", 'val' => 178, 'name' => "optimize-spreadcall", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 2, 'format' => ["JOF_BYTE"]],
        179 => ['op' => "JSOP_THROWSETCALLEE", 'val' => 179, 'name' => "throwsetcallee", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ["JOF_SET", "JOF_BYTE"]],
        180 => ['op' => "JSOP_PUSHVARENV", 'val' => 180, 'name' => "pushvarenv", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ["JOF_SCOPE"]],
        181 => ['op' => "JSOP_POPVARENV", 'val' => 181, 'name' => "popvarenv", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        182 => ['op' => "JSOP_UNUSED182", 'val' => 182, 'name' => "unused182", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        183 => ['op' => "JSOP_UNUSED183", 'val' => 183, 'name' => "unused183", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        184 => ['op' => "JSOP_CALLPROP", 'val' => 184, 'name' => "callprop", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP", "JOF_TYPESET"]],
        185 => ['op' => "JSOP_FUNCTIONTHIS", 'val' => 185, 'name' => "functionthis", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        186 => ['op' => "JSOP_GLOBALTHIS", 'val' => 186, 'name' => "globalthis", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        187 => ['op' => "JSOP_UNUSED187", 'val' => 187, 'name' => "unused187", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        188 => ['op' => "JSOP_UINT24", 'val' => 188, 'name' => "uint24", 'image' => NULL, 'len' => 4, 'use' => 0, 'def' => 1, 'format' => ["JOF_UINT24"]],
        189 => ['op' => "JSOP_CHECKTHIS", 'val' => 189, 'name' => "checkthis", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ["JOF_BYTE"]],
        190 => ['op' => "JSOP_CHECKRETURN", 'val' => 190, 'name' => "checkreturn", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 0, 'format' => ["JOF_BYTE"]],
        191 => ['op' => "JSOP_CHECKTHISREINIT", 'val' => 191, 'name' => "checkthisreinit", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ["JOF_BYTE"]],
        192 => ['op' => "JSOP_UNUSED192", 'val' => 192, 'name' => "unused192", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        193 => ['op' => "JSOP_CALLELEM", 'val' => 193, 'name' => "callelem", 'image' => NULL, 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_ELEM", "JOF_TYPESET", "JOF_LEFTASSOC"]],
        194 => ['op' => "JSOP_MUTATEPROTO", 'val' => 194, 'name' => "mutateproto", 'image' => NULL, 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ["JOF_BYTE"]],
        195 => ['op' => "JSOP_GETXPROP", 'val' => 195, 'name' => "getxprop", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP", "JOF_TYPESET"]],
        196 => ['op' => "JSOP_TYPEOFEXPR", 'val' => 196, 'name' => "typeofexpr", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_DETECTING"]],
        197 => ['op' => "JSOP_FRESHENLEXICALENV", 'val' => 197, 'name' => "freshenlexicalenv", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        198 => ['op' => "JSOP_RECREATELEXICALENV", 'val' => 198, 'name' => "recreatelexicalenv", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        199 => ['op' => "JSOP_PUSHLEXICALENV", 'val' => 199, 'name' => "pushlexicalenv", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ["JOF_SCOPE"]],
        200 => ['op' => "JSOP_POPLEXICALENV", 'val' => 200, 'name' => "poplexicalenv", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        201 => ['op' => "JSOP_DEBUGLEAVELEXICALENV", 'val' => 201, 'name' => "debugleavelexicalenv", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        202 => ['op' => "JSOP_INITIALYIELD", 'val' => 202, 'name' => "initialyield", 'image' => NULL, 'len' => 4, 'use' => 1, 'def' => 1, 'format' => ["JOF_UINT24"]],
        203 => ['op' => "JSOP_YIELD", 'val' => 203, 'name' => "yield", 'image' => NULL, 'len' => 4, 'use' => 2, 'def' => 1, 'format' => ["JOF_UINT24"]],
        204 => ['op' => "JSOP_FINALYIELDRVAL", 'val' => 204, 'name' => "finalyieldrval", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 0, 'format' => ["JOF_BYTE"]],
        205 => ['op' => "JSOP_RESUME", 'val' => 205, 'name' => "resume", 'image' => NULL, 'len' => 3, 'use' => 2, 'def' => 1, 'format' => ["JOF_UINT8", "JOF_INVOKE"]],
        206 => ['op' => "JSOP_ARRAYPUSH", 'val' => 206, 'name' => "arraypush", 'image' => NULL, 'len' => 1, 'use' => 2, 'def' => 0, 'format' => ["JOF_BYTE"]],
        207 => ['op' => "JSOP_FORCEINTERPRETER", 'val' => 207, 'name' => "forceinterpreter", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        208 => ['op' => "JSOP_DEBUGAFTERYIELD", 'val' => 208, 'name' => "debugafteryield", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        209 => ['op' => "JSOP_UNUSED209", 'val' => 209, 'name' => "unused209", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        210 => ['op' => "JSOP_UNUSED210", 'val' => 210, 'name' => "unused210", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        211 => ['op' => "JSOP_UNUSED211", 'val' => 211, 'name' => "unused211", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        212 => ['op' => "JSOP_GENERATOR", 'val' => 212, 'name' => "generator", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        213 => ['op' => "JSOP_BINDVAR", 'val' => 213, 'name' => "bindvar", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        214 => ['op' => "JSOP_BINDGNAME", 'val' => 214, 'name' => "bindgname", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_NAME", "JOF_SET", "JOF_GNAME"]],
        215 => ['op' => "JSOP_INT8", 'val' => 215, 'name' => "int8", 'image' => NULL, 'len' => 2, 'use' => 0, 'def' => 1, 'format' => ["JOF_INT8"]],
        216 => ['op' => "JSOP_INT32", 'val' => 216, 'name' => "int32", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_INT32"]],
        217 => ['op' => "JSOP_LENGTH", 'val' => 217, 'name' => "length", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ["JOF_ATOM", "JOF_PROP", "JOF_TYPESET"]],
        218 => ['op' => "JSOP_HOLE", 'val' => 218, 'name' => "hole", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE"]],
        219 => ['op' => "JSOP_UNUSED219", 'val' => 219, 'name' => "unused219", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        220 => ['op' => "JSOP_UNUSED220", 'val' => 220, 'name' => "unused220", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        221 => ['op' => "JSOP_UNUSED221", 'val' => 221, 'name' => "unused221", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        222 => ['op' => "JSOP_UNUSED222", 'val' => 222, 'name' => "unused222", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        223 => ['op' => "JSOP_UNUSED223", 'val' => 223, 'name' => "unused223", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        224 => ['op' => "JSOP_REST", 'val' => 224, 'name' => "rest", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ["JOF_BYTE", "JOF_TYPESET"]],
        225 => ['op' => "JSOP_TOID", 'val' => 225, 'name' => "toid", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ["JOF_BYTE"]],
        226 => ['op' => "JSOP_IMPLICITTHIS", 'val' => 226, 'name' => "implicitthis", 'image' => "", 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ["JOF_ATOM"]],
        227 => ['op' => "JSOP_LOOPENTRY", 'val' => 227, 'name' => "loopentry", 'image' => NULL, 'len' => 2, 'use' => 0, 'def' => 0, 'format' => ["JOF_UINT8"]],
        228 => ['op' => "JSOP_TOSTRING", 'val' => 228, 'name' => "tostring", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ["JOF_BYTE"]],
        229 => ['op' => "JSOP_NOP_DESTRUCTURING", 'val' => 229, 'name' => "nop-destructuring", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
        230 => ['op' => "JSOP_JUMPTARGET", 'val' => 230, 'name' => "jumptarget", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ["JOF_BYTE"]],
    ];
}
